### PR TITLE
Ngx admin with the build script

### PR DESCRIPTION
**Pull request by EmmanuelObua**

### CODE REVIEW

**Comment by twschiller** [comment]
@EmmanuelObua please look into the merge conflicts. I want to see if this builds now that that the other one has been merged in. (Maybe Vercel only supports 1 PR branch at a time?)

**Comment by twschiller** [comment]
I just updated our billing information on Vercel, so it may work now

**Comment by EmmanuelObua** [comment]
Ok, let me update the PR

**Comment by EmmanuelObua** [comment]
@twschiller this has been deployed successfully

**Pull request merged**
